import type { EventEmitter } from 'node:events';
export declare const ERROR_CODES: Readonly<Record<string, string>>;
export declare class PlogallError extends Error { code: string; platform?: string; feature?: string; cause?: unknown; details?: unknown; constructor(code: string, message: string, options?: { platform?: string; feature?: string; cause?: unknown; details?: unknown }); }
export interface UniversalUser { id: string; name: string | null; username: string | null; platform: string; raw: unknown; }
export interface UniversalChat { id: string; type: string; name: string | null; platform: string; raw: unknown; }
export interface UniversalMessage { id: string; platform: string; type: string; text: string; timestamp: number; user: UniversalUser; chat: UniversalChat; media: unknown; capabilities: Record<string, boolean>; raw: unknown; reply(content: unknown, options?: unknown): Promise<unknown>; send(content: unknown, options?: unknown): Promise<unknown>; react(text: string): Promise<unknown>; edit(content: unknown, options?: unknown): Promise<unknown>; delete(): Promise<unknown>; }
export declare function decorateMessage(message: Omit<UniversalMessage, 'reply' | 'send' | 'react' | 'edit' | 'delete'>, adapter: any): UniversalMessage;
export declare function wrapError(error: unknown, fallback: { code: string; message: string; feature?: string }, platform: string): PlogallError;
export interface UniversalContent { type: 'text'; text: string; buttons: Array<{ label: string; action: string; [key: string]: unknown }>; media: Array<{ type: string; url: string; [key: string]: unknown }>; metadata: Record<string, unknown>; }
export declare class MessageBuilder { text(value: unknown): this; image(url: string, options?: Record<string, unknown>): this; video(url: string, options?: Record<string, unknown>): this; document(url: string, options?: Record<string, unknown>): this; button(label: string, action: string, options?: Record<string, unknown>): this; metadata(values: Record<string, unknown>): this; build(): UniversalContent; }
export declare const Message: { text(value: unknown): MessageBuilder; builder(): MessageBuilder; };
export declare function message(value: unknown): UniversalContent | string;
export declare function renderMessage(content: unknown, capabilities?: Record<string, boolean>, platform?: string): { text: string; buttons?: unknown[]; media?: unknown[]; metadata?: Record<string, unknown>; degraded: boolean; omittedFeatures: string[]; };
export declare class MemoryStore { get(key: string): Promise<unknown>; set(key: string, value: unknown): Promise<unknown>; delete(key: string): Promise<boolean>; values(): Promise<unknown[]>; }
export declare class FileStore { constructor(directory?: string); get(key: string): Promise<unknown>; set(key: string, value: unknown): Promise<unknown>; delete(key: string): Promise<boolean>; values(): Promise<unknown[]>; }
export declare class IdentityStore { constructor(store?: MemoryStore); link(canonicalId: string, platform: string, platformId: string, options?: { verified?: boolean }): Promise<unknown>; resolve(platform: string, platformId: string): string | null; aliases(canonicalId: string): Array<{ platform: string; platformId: string }>; }
export declare class DeliveryManager extends EventEmitter { constructor(options?: { maxAttempts?: number; backoffMs?: number; sleep?: (ms: number) => Promise<void> }); status(key: string): unknown; markDegraded(): void; metrics(): Record<string, number>; send(options: { platform: string; chat: string | number; content: unknown; send: () => Promise<unknown>; idempotencyKey?: string; maxAttempts?: number }): Promise<unknown>; }
export declare class WorkflowBuilder { onMessage(): this; when(predicate: ((message: UniversalMessage) => boolean | Promise<boolean>) | string): this; ask(key: string, prompt: string | ((values: Record<string, unknown>) => string)): this; step(key: string, handler: (context: { message: UniversalMessage; state: Record<string, unknown> }) => unknown): this; reply(value: string | ((values: Record<string, unknown>) => string)): this; complete(handler: (context: { message: UniversalMessage; state: Record<string, unknown> }) => unknown): this; }
export declare class WorkflowEngine extends EventEmitter { constructor(store?: MemoryStore); create(name: string): WorkflowBuilder; handle(message: UniversalMessage): Promise<boolean>; }
export interface Adapter { name: string; state?: string; connect(): Promise<unknown>; disconnect?(): Promise<unknown>; attach(app: Plogall): void; capabilities(): Record<string, boolean>; sendMessage(chat: string | number, content: unknown, options?: unknown): Promise<unknown>; render?(content: unknown): unknown; }
export declare class Plogall extends EventEmitter { readonly delivery: DeliveryManager; readonly identity: IdentityStore; readonly workflows: WorkflowEngine; constructor(options?: { debug?: boolean; store?: MemoryStore; delivery?: DeliveryManager; identity?: IdentityStore; workflows?: WorkflowEngine }); use(adapter: Adapter): this; adapter(name: string): Adapter; adapters(): Adapter[]; middleware(fn: (message: UniversalMessage, next: () => Promise<unknown>) => unknown): this; onMessage(handler: (message: UniversalMessage) => unknown): this; workflow(name: string): WorkflowBuilder; capabilities(platform?: string): Record<string, unknown>; metrics(): unknown; start(): Promise<this>; stop(): Promise<void>; send(options: { platform: string; chat: string | number; message?: unknown; idempotencyKey?: string; [key: string]: unknown }): Promise<unknown>; }
